version: "3.8"
services:

  python-executor:
    build:
      context: ./services/python-executor
    ports:
      - ":5000"

  # ts-executor:
  #   build:
  #     context: ./services/ts-executor
  #   ports:
  #     - ":4000"

  # go-executor:
  #   build:
  #     context: ./services/go-executor
  #   ports:
  #     - ":6000"
