version: "3.8"
services:

  python-executor:
    build:
      context: ./services/python-executor
    ports:
      - ":5000"
    environment:
      # Define la URL generada automáticamente para este servicio
      - SERVICE_FQDN_PYTHON_EXECUTOR=/
      # Si necesitas usar la URL en otro lugar, define otra variable
      - SERVICE_URL_PYTHON_EXECUTOR=$SERVICE_FQDN_PYTHON_EXECUTOR
